server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        allow 172.22.0.10;
        deny all;
        try_files $uri $uri/ =404;
    }
}
