upstream web-robin {
    # round robin algorithm
    server server1:80 fail_timeout=3s;
    server server2:80 fail_timeout=3s;
}

upstream web-least-conn {
    # least connection algorithm
    least_conn;
    server server1:80 fail_timeout=3s;
    server server2:80 fail_timeout=3s;
}

upstream web-ip-hash {
    # ip hash algorithm
    # The method guarantees that requests from the same address get to the same server unless it is not available
    ip_hash;
    server server1:80 fail_timeout=3s;
    server server2:80 fail_timeout=3s;
}

server {
    listen 8080;
    server_name _;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 3s;
        proxy_pass http://web-robin;
    }
}

server {
    listen 8081;
    server_name _;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 3s;
        proxy_pass http://web-least-conn;
    }
}

server {
    listen 8082;
    server_name _;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 3s;
        proxy_pass http://web-ip-hash;
    }
}
